# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='timeToRead',
            field=models.CharField(default=datetime.datetime(2016, 6, 26, 20, 37, 56, 371297, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
