# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160720_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
